#Write a python code that shows the user input for grocery items
print ("Enter grocery items")
print ("Enter first item")
item1 = input ()
print ("Enter first item price")
item1price = float (input ())
print ("Enter second item")
item2 = input ()
print ("Enter item2 price")
item2price = float (input ())
print ("Enter third item")
item3 = input ()
print ("Enter item3 price")
item3price = float (input ())
print ("Final details" + " " + item1 + str(item1price) + " " + item2 + " " + str(item2price) + " "  + item3 + " " + str(item3price))
